inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'doc/**/*'
    - 'config/initializers/simple_form*'
    - 'db/migrate/*'
    - 'vendor/**/*'

Style/AsciiComments:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Metrics/AbcSize:
  Max: 20

Style/CommentAnnotation:
  Enabled: false
