language: ruby
rvm:
  - 2.4.5
env:
  - RAILS_ENV=test
before_script:
  - cp ./config/database.yml.travis ./config/database.yml
  - bundle exec rake db:create db:migrate RAILS_ENV=test
  - bundle exec rubocop
