defaults: &defaults
  title: AML
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'localhost' %>

  bugsnag_api_key: "88eff6a1190d47f39a44cead0a437815"

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
staging:
  <<: *defaults
  default_url_options:
    host: aml.stage.bang8.ru

  smtp_settings:
    user_name: 'cd713a3aaf6357'
    password: '3e201311417506'
    address: 'smtp.mailtrap.io'
    domain: 'smtp.mailtrap.io'
    port: '2525'
    authentication: :cram_md5
