defaults: &defaults
  title: AML
  default_url_options: &default_url_options
    host: <%= ENV['APP_HOST'] || 'localhost' %>

  bugsnag_api_key: "88eff6a1190d47f39a44cead0a437815"
  mailer:
    from: support@kassa.cc

  notification_documentation_url: 'https://docs.google.com/spreadsheets/d/15MKv6fq6u0bwHRXtvXHIDNNZkLfKdwl4u1sbwIOihHA/edit#gid=0'

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
  default_url_options:
    host: aml.kassa.cc
staging:
  <<: *defaults
  default_url_options:
    host: aml.stage.bang8.ru
